"""Write the analysis as a C header for the card firmware."""

import numpy as np

from . import synth
from .config import CATEGORIES, CATEGORY_NAMES


def choose_templates(elements, X, max_per_cat):
    """Pick up to max_per_cat elements per category, spread from typical to
    unusual, leaving out the most extreme 10% as likely mis-segmentations."""
    chosen = []
    for c in CATEGORIES:
        idx = [i for i, m in enumerate(elements) if m["label"] == c]
        if not idx:
            continue
        sub = X[idx]
        d = ((sub - sub.mean(0)) ** 2).sum(1)
        order = [idx[i] for i in np.argsort(d)]
        if len(order) >= 10:
            order = order[: int(np.ceil(0.9 * len(order)))]
        if len(order) > max_per_cat:
            pick = np.linspace(0, len(order) - 1, max_per_cat).round().astype(int)
            order = [order[i] for i in pick]
        chosen.extend(order)
    return chosen


def _cdf16(dist):
    """Probabilities -> cumulative uint16 table ending at exactly 65535."""
    c = np.cumsum(dist)
    c = np.round(c / c[-1] * 65535).astype(int)
    c[-1] = 65535
    return c.tolist()


def _arr(v):
    return "{" + ", ".join(str(int(x)) for x in v) + "}"


def header(templates, model, gap_ms, ioi_ratio_hist, elements_per_s, sources):
    cat_index = {c: i for i, c in enumerate(CATEGORIES)}
    templates = sorted(templates, key=lambda q: cat_index[q["category"]])
    starts, n = [], 0
    for c in CATEGORIES:
        starts.append(n)
        n += sum(1 for q in templates if q["category"] == c)
    starts.append(n)

    L = []
    w = L.append
    w("// Budgie analysis data. Generated by tools/budgie_analysis - do not edit by hand.")
    w("// Sources:")
    for s in sources:
        w(f"//   {s}")
    w("#ifndef BUDGIE_DATA_H")
    w("#define BUDGIE_DATA_H")
    w("")
    w("#include <stdint.h>")
    w("")
    w(f"#define BUDGIE_N_CATEGORIES {len(CATEGORIES)}")
    w(f"#define BUDGIE_N_F0_POINTS {synth.N_F0}")
    w(f"#define BUDGIE_N_AMP_POINTS {synth.N_AMP}")
    w(f"#define BUDGIE_N_HARMONICS {synth.N_HARM}")
    w(f"#define BUDGIE_MAX_ORDER {max([len(r['context']) for r in model] + [0])}")
    w("")
    w("enum budgie_category {")
    for c in CATEGORIES:
        w(f"    BUDGIE_{c}, // {CATEGORY_NAMES[c]}")
    w("};")
    w("")
    w("// One element template. Times are fractions of the duration (0..255),")
    w("// amplitudes and mixes are 0..255, frequencies in Hz.")
    w("typedef struct {")
    w("    uint8_t category;       // enum budgie_category")
    w("    uint8_t n_f0;           // f0 breakpoints used; 0 = unpitched (noise only)")
    w("    uint16_t dur_ms;")
    w("    uint8_t f0_t[BUDGIE_N_F0_POINTS];")
    w("    uint16_t f0_hz[BUDGIE_N_F0_POINTS];")
    w("    uint8_t amp_t[BUDGIE_N_AMP_POINTS];")
    w("    uint8_t amp[BUDGIE_N_AMP_POINTS];")
    w("    uint16_t am_rate_hz;")
    w("    uint8_t am_depth;")
    w("    uint8_t harm[BUDGIE_N_HARMONICS]; // relative amplitude of harmonics 1..N")
    w("    uint8_t noise_mix;      // 0 = pure tone, 255 = pure noise")
    w("    uint16_t noise_centre_hz;")
    w("    uint16_t noise_bw_hz;")
    w("    uint8_t level;          // loudness relative to the loudest elements")
    w("} budgie_element_t;")
    w("")
    w(f"#define BUDGIE_N_ELEMENTS {len(templates)}")
    w("static const budgie_element_t budgie_elements[BUDGIE_N_ELEMENTS] = {")
    for q in templates:
        w(f"    {{BUDGIE_{q['category']}, {q['n_f0']}, {q['dur_ms']}, {_arr(q['f0_t'])}, {_arr(q['f0_hz'])}, "
          f"{_arr(q['amp_t'])}, {_arr(q['amp'])}, {q['am_rate_hz']}, {q['am_depth']}, {_arr(q['harm'])}, "
          f"{q['noise_mix']}, {q['noise_centre_hz']}, {q['noise_bw_hz']}, {q['level']}}},")
    w("};")
    w("")
    w("// budgie_elements[budgie_category_start[c] .. budgie_category_start[c+1]-1] are category c")
    w(f"static const uint16_t budgie_category_start[BUDGIE_N_CATEGORIES + 1] = {_arr(starts)};")
    w("")
    w("// Variable-order sequence model. Find the longest context matching the most")
    w("// recent elements (ctx[0] is the oldest, ctx[order-1] the most recent), then")
    w("// draw the next category from its cumulative table (compare a uint16 random")
    w("// number against cdf[]). Entries are sorted longest context first; the last")
    w("// entry has order 0 and always matches.")
    w("typedef struct {")
    w("    uint8_t order;")
    w("    uint8_t ctx[BUDGIE_MAX_ORDER > 0 ? BUDGIE_MAX_ORDER : 1];")
    w("    uint16_t cdf[BUDGIE_N_CATEGORIES];")
    w("} budgie_context_t;")
    w("")
    maxo = max([len(r["context"]) for r in model] + [1])
    w(f"#define BUDGIE_N_CONTEXTS {len(model)}")
    w("static const budgie_context_t budgie_contexts[BUDGIE_N_CONTEXTS] = {")
    for r in model:
        ctx = [cat_index[ch] for ch in r["context"]] + [0] * (maxo - len(r["context"]))
        w(f"    {{{len(r['context'])}, {_arr(ctx)}, {_arr(_cdf16(r['dist']))}}}, // '{r['context']}' n={r['count']}")
    w("};")
    w("")
    w("// Median silence (ms) from the end of an element of category [a] to the start")
    w("// of the next one of category [b]; 0xFFFF where that pair was never seen.")
    w("static const uint16_t budgie_gap_ms[BUDGIE_N_CATEGORIES][BUDGIE_N_CATEGORIES] = {")
    for row in gap_ms:
        w("    " + _arr([0xFFFF if v is None else max(0, round(v)) for v in row]) + ",")
    w("};")
    w("")
    hist = np.array(ioi_ratio_hist, float)
    cdf = _cdf16(hist / hist.sum()) if hist.sum() > 0 else [0] * len(hist)
    w("// Rhythm: cumulative distribution of IOI ratios r = IOI_k / (IOI_k + IOI_k+1),")
    w(f"// in {len(hist)} equal bins over 0..1. r = 0.5 means two equal intervals.")
    w(f"#define BUDGIE_N_IOI_BINS {len(hist)}")
    w(f"static const uint16_t budgie_ioi_ratio_cdf[BUDGIE_N_IOI_BINS] = {_arr(cdf)};")
    w("")
    w(f"#define BUDGIE_ELEMENTS_PER_S_X100 {int(round(100 * elements_per_s))}")
    w("")
    w("#endif // BUDGIE_DATA_H")
    return "\n".join(L) + "\n"
