// Budgie - Workshop Computer card 114
//
// Phase 1: the Phonetics Lab. Pick one of the seven budgerigar warble
// element categories, pick a recorded variant, bend its most telling
// parameter, and trigger it. See README.md for the panel, and
// documentation/proposals/budgie.md for where this is going.
//
// The element templates come from budgie_data.h, generated by
// tools/budgie_analysis from recordings. The synth voice is budgie_voice.h,
// whose Python twin is tools/budgie_analysis/budgie_analysis/synth.py.

#include "ComputerCard.h"

#ifdef BUDGIE_PROFILE
#include "hardware/structs/systick.h"
#endif

#define BUDGIE_RAM_FUNC(f) __not_in_flash_func(f)
#include "budgie_voice.h"

using namespace budgie;

// Silence while the DAC and switch settle. The switch is read once, after
// this, for the boot mode (the Voder / Nibble-KO rule: never "Down seen at
// any point", because it reads Down until it settles).
static constexpr int32_t kBootMute = 24000;      // 0.5 s

// Control work (knobs, CVs, LEDs) every 4 samples, matching ComputerCard's
// 4-state input mux so the reads don't beat against it.
static constexpr int32_t kPanelDiv = 4;

static constexpr int32_t kOnsetPulse = 96;       // 2 ms trigger on Pulse Out 1
static constexpr int32_t kAutoGap = 12000;       // Z up: 250 ms rest between auto-plays
static constexpr int32_t kKnobDeadband = 96;     // Y centre = template as recorded
static constexpr int32_t kClickSpacing = 864;    // 18 ms between clicks in an F train
static constexpr int32_t kMaxClicks = 8;
static constexpr int32_t kCatHysteresis = 48;

// Syllable coda: the end of a budgie syllable tends to be longer, quieter
// and lower than its nucleus (Mann et al. 2021).
static constexpr int32_t kCodaPitch = -16384;    // -3 semitones, log2 Q16
static constexpr int32_t kCodaDur = 333;         // x1.3
static constexpr int32_t kCodaLevel = 128;       // -6 dB

class Budgie : public ComputerCard
{
public:
    Budgie()
    {
        InitTables();
        Prepare();
        log2_1khz_ = Log2Q16(1000.0f);
    }

    virtual void __not_in_flash_func(ProcessSample)() override
    {
#ifdef BUDGIE_PROFILE
        uint32_t t0 = systick_hw->cvr;
        Run1();
        uint32_t dt = (t0 - systick_hw->cvr) & 0xFFFFFF;
        if (dt > peak_cycles_) peak_cycles_ = dt;
#else
        Run1();
#endif
    }

private:
    void __not_in_flash_func(Run1)()
    {
        if (boot_ > 0) {
            Boot();
            return;
        }

        // Triggers are edges, so check them every sample. Z down is momentary
        // and springs back to middle; Z up (latched) plays on its own.
        bool trig = (SwitchVal() == Switch::Down && SwitchChanged()) || PulseIn1RisingEdge();
        if (SwitchVal() == Switch::Up) {
            if (v1_.Active() || v2_.Active())
                auto_wait_ = kAutoGap;
            else if (--auto_wait_ <= 0)
                trig = true;
        }
        bool p2_patched = Connected(Input::Pulse2);

        // Out 1: the element on its own. Out 2: the same element as a whole
        // syllable, so the two can be compared (or Pulse In 2 drives it alone).
        // Out 2's trigger runs a sample later, to keep the work of the two
        // triggers out of the same sample.
        if (v2_pending_) {
            Trigger(v2_, true);
            v2_pending_ = false;
        }
        if (trig) Trigger(v1_, false);
        if (p2_patched ? PulseIn2RisingEdge() : trig) v2_pending_ = true;

        // at most one element start per sample: it is the expensive sample
        AudioOut1((int16_t)v1_.Process());
        AudioOut2((int16_t)v2_.Process(!v1_.Onset()));

        if (v1_.Onset()) pulse_ = kOnsetPulse;
        PulseOut1(pulse_ > 0);
        if (pulse_ > 0) pulse_--;
        PulseOut2(v1_.Sounding());

        // panel work, one part per sample across the 4-sample cycle
        if (++panel_ >= kPanelDiv) panel_ = 0;
        if (panel_ == 0) ReadKnobs();
        else if (panel_ == 1) UpdateCVOuts();
        else if (panel_ == 2) UpdateLeds();
    }

    void Boot()
    {
        boot_--;
        AudioOut1(0);
        AudioOut2(0);
        PulseOut1(false);
        PulseOut2(false);
        // LED chase while waiting
        int lit = (kBootMute - boot_) * 6 / kBootMute;
        for (int i = 0; i < 6; i++) LedBrightness(i, i == lit ? 2000 : 0);
        if (boot_ == 0) {
            // Reserved for the Aviary mode (Phase 2): hold Z down at power-on.
            alt_boot_ = SwitchVal() == Switch::Down;
            main_ = KnobVal(Knob::Main);
            x_ = KnobVal(Knob::X);
            y_ = KnobVal(Knob::Y);
            cat_ = main_ * BUDGIE_N_CATEGORIES / 4096;
            for (int i = 0; i < 6; i++) LedOff(i);
        }
    }

    // Read the knobs and update the selection. Called every kPanelDiv samples.
    void ReadKnobs()
    {
        main_ += (KnobVal(Knob::Main) - main_) >> 3;
        x_ += (KnobVal(Knob::X) - x_) >> 3;
        y_ += (KnobVal(Knob::Y) - y_) >> 3;

        // category: seven zones across Main, with hysteresis
        int32_t width = 4096 / BUDGIE_N_CATEGORIES;
        if (main_ < cat_ * width - kCatHysteresis || main_ > (cat_ + 1) * width + kCatHysteresis) {
            cat_ = main_ / width;
            if (cat_ >= BUDGIE_N_CATEGORIES) cat_ = BUDGIE_N_CATEGORIES - 1;
        }
    }

    // Index of the selected template.
    int Selected() const
    {
        int c = PlayableCategory(cat_);
        int first = budgie_category_start[c];
        int n = budgie_category_start[c + 1] - first;
        int v = (int)(x_ * n >> 12);
        return first + (v < n ? v : n - 1);
    }

    // Categories with no templates in the data fall back to the nearest one that has some.
    static int PlayableCategory(int c)
    {
        for (int d = 0; d < BUDGIE_N_CATEGORIES; d++) {
            for (int s = -1; s <= 1; s += 2) {
                int k = c + s * d;
                if (k >= 0 && k < BUDGIE_N_CATEGORIES &&
                    budgie_category_start[k + 1] > budgie_category_start[k])
                    return k;
            }
        }
        return 0;
    }

    // Y knob with a centre deadband: -2048..2047, 0 = as recorded.
    int32_t Morph() const
    {
        int32_t m = y_ - 2048;
        if (m > kKnobDeadband) return (m - kKnobDeadband) * 2048 / (2048 - kKnobDeadband);
        if (m < -kKnobDeadband) return (m + kKnobDeadband) * 2048 / (2048 - kKnobDeadband);
        return 0;
    }

    Mods BaseMods(int category)
    {
        Mods m;
        // CV 1: pitch, roughly 1 V/oct (about 341 counts per volt, uncalibrated)
        m.pitch_q16 = CVIn1() * 192;
        // CV 2: duration, x0.5 .. x2 across the CV range
        m.dur_q8 = (int32_t)Exp2Q16((8 << 16) + CVIn2() * 32);
        int32_t y = Morph();
        switch (category) {
        case BUDGIE_A: m.mix_q8 = 256 + y / 8; break;            // harshness
        case BUDGIE_B:
        case BUDGIE_G: m.fm_depth_q8 = 256 + y / 8; break;       // pitch excursion x0..x2
        case BUDGIE_C:
        case BUDGIE_D: m.harm_q8 = 256 + y / 8; break;           // upper harmonics x0..x2
        case BUDGIE_E: m.noise_q16 = y * 32; break;              // noise colour +/- 1 octave
        case BUDGIE_F: if (y < 0) m.noise_q16 = y * 32; break;   // left: darker; right: trains
        }
        return m;
    }

    void Trigger(Voice &v, bool syllable)
    {
        int idx = Selected();
        int c = budgie_elements[idx].category;
        Mods m = BaseMods(c);
        v.Cut();

        if (c == BUDGIE_F) {
            int32_t y = Morph();
            int clicks = y > 0 ? 1 + y * (kMaxClicks - 1) / 2048 : 1;
            int32_t gap = kClickSpacing - (int32_t)budgie_elements[idx].dur_ms * 48;
            if (gap < 0) gap = 0;
            for (int i = 0; i < clicks; i++) v.Enqueue(idx, m, i ? gap : 0);
            return;
        }

        bool tonal = c == BUDGIE_B || c == BUDGIE_C || c == BUDGIE_D || c == BUDGIE_G;
        if (syllable && tonal) {
            // consonant-like onset, the element as nucleus, then a softer, lower, longer coda
            int nf = budgie_category_start[BUDGIE_F + 1] - budgie_category_start[BUDGIE_F];
            if (nf > 0) {
                int onset = budgie_category_start[BUDGIE_F] + (int)(x_ * nf >> 12);
                v.Enqueue(onset, BaseMods(BUDGIE_F), 0);
            }
            v.Enqueue(idx, m, 0);
            Mods coda = m;
            coda.pitch_q16 += kCodaPitch;
            coda.dur_q8 = coda.dur_q8 * kCodaDur >> 8;
            coda.level_q8 = kCodaLevel;
            v.Enqueue(idx, coda, 0);
        } else {
            v.Enqueue(idx, m, 0);
        }
    }

    void UpdateCVOuts()
    {
        // CV 1: Bird 1 pitch, 1 V/oct, 0 V = 1 kHz, held through silences
        int32_t mv = (int32_t)(((int64_t)(v1_.PitchLog2() - log2_1khz_) * 1000) >> 16);
        CVOut1Millivolts(mv);
#ifdef BUDGIE_PROFILE
        // Profiling build: CV Out 2 shows the slowest sample seen, 0..2047 for
        // 0..3000 cycles (the whole 48 kHz budget at 144 MHz). LED 5 lights
        // above 80% of the budget. Decays slowly so it can be read on a meter.
        CVOut2((int16_t)(peak_cycles_ * 2047 / 3000 > 2047 ? 2047 : peak_cycles_ * 2047 / 3000));
        if (peak_cycles_ > 0) peak_cycles_ -= peak_cycles_ >> 12;
#else
        CVOut2((int16_t)(v1_.Envelope() >> 5));  // CV 2: Bird 1 envelope
#endif
    }

    void UpdateLeds()
    {
        int32_t env = v1_.Envelope();

        // LEDs 0-5 show categories A-F; soft calls (G) light all six dimly.
        // Brightness follows Bird 1's envelope.
        int c = PlayableCategory(cat_);
        int32_t glow = env >> 4;
        for (int i = 0; i < 6; i++) {
            int32_t b = 0;
#ifdef BUDGIE_PROFILE
            if (i == 5) {
                LedOn(5, peak_cycles_ > 2400);
                continue;
            }
#endif
            if (c == BUDGIE_G)
                b = 250 + (glow >> 2);
            else if (i == c)
                b = 1200 + glow;
            if (b > 4095) b = 4095;
            LedBrightness(i, (uint16_t)b);
        }
    }

    Voice v1_, v2_;
    int32_t boot_ = kBootMute;
    bool alt_boot_ = false, v2_pending_ = false;
    int32_t panel_ = 0, pulse_ = 0, auto_wait_ = 0;
    int32_t main_ = 0, x_ = 0, y_ = 2048;
    int cat_ = 0;
    int32_t log2_1khz_ = 0;
#ifdef BUDGIE_PROFILE
    uint32_t peak_cycles_ = 0;
#endif
};

int main()
{
    set_sys_clock_khz(144000, true);
#ifdef BUDGIE_PROFILE
    systick_hw->rvr = 0xFFFFFF;
    systick_hw->cvr = 0;
    systick_hw->csr = 0x5;  // enabled, counting processor clock cycles
#endif
    static Budgie card;
    card.EnableNormalisationProbe();
    card.Run();
    return 0;
}
